services:
  - type: web
    name: replygo
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
    healthCheckPath: /
    numReplicas: 1
    scaling:
      minInstances: 1
      maxInstances: 1
